<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <EnableNUnitRunner>true</EnableNUnitRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.*" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TddGuard.Dotnet/TddGuard.Dotnet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <TestingPlatformBuilderHook Include="TddGuard.Dotnet">
      <DisplayName>TddGuard.Dotnet</DisplayName>
      <TypeFullName>TestingPlatformBuilderHook</TypeFullName>
    </TestingPlatformBuilderHook>
  </ItemGroup>

</Project>
