<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace></RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.core" Version="3.*">
      <ExcludeAssets>build</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3.assert" Version="3.*" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.*" />
    <PackageReference Include="xunit.v3.core.mtp-v1" Version="3.*">
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="TddGuard.Dotnet" Version="0.1.0-local" />
  </ItemGroup>

</Project>
